# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7aedcc4b3e6ee60c3ccced3f07fe65f2a5823a2b4530b1075919f760bdcc96e96d2a3ed7ea2648c39f448cf7bf0980c3731e4b42045e4a38f08993d82b72d4f

test:
  secret_key_base: 75ee17198579d81a87ae49450512e6b67ddc03eb187e628c02b17ef723178572edbf5fef525ef20407330184588a6b21e727396caf1caf19dd7811246e2a6181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
